### ISSUE TITLE
Anything new?

### ISSUE THREAD

**Issue by iHumus** [stiggy87/ZynqBTC#2]
Do you have a working firmware?
Can you share the .bit file or something similar to use with the ZedBoard?

**Comment by stiggy87** [comment]
Hi iHumus,

Sadly, after starting the project, I became very busy with my work and I have basically do not work on it anymore at this moment. So I do not have any working firmware.

There may be forks that people created that might have gotten it to bitstream.

Sorry for any inconvenience.
